version: 0.0
os: linux
files:
  - source: /
    destination: /appdir
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
      ignoreErrors: true
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
